### ISSUE TITLE
Can't enter post code

### ISSUE THREAD

**Issue by nikrb** [chingu-voyages/v8-bears-team-14#66]
The zip/post code field only seems to accept zip's

**Comment by g1st** [comment]
This comes directly from stripe's API and is dynamic. I mean if you would add [UK card number](https://stripe.com/docs/testing#international-cards) for example `4000 0082 6000 0000` then even placeholder text in `Postal / ZIP code` input field would change to `WS11 1DB` and you would be able to type letters in the field.
